inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/structure.sql'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'node_modules/**/*'

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideParens:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
