FROM ruby:4.0.1-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      libpq-dev \
      postgresql-client \
      git \
    && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

COPY bin/docker-entrypoint-dev /usr/local/bin/docker-entrypoint-dev

CMD ["bin/rails", "server", "-b", "0.0.0.0"]



